config/routes.rb
Favorite::Application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :twitter_accounts do
    resources :keywords
  end

  authenticated do
    root to: "twitter_accounts#index", as: :authenticated_root
  end

  root to: "main#index"
end

app/models/favorited_tweet.rb
class FavoritedTweet < ActiveRecord::Base
  belongs_to :twitter_account
  scope :sorted, ->{ order("posted_at DESC") }
  scope :recent, ->{ limit(30) }
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :twitter_account
  validates :text, presence: true
end

app/models/twitter_account.rb
class TwitterAccount < ActiveRecord::Base
  belongs_to :user
  has_many :keywords
  has_many :favorited_tweets

  def favorite_tweets!(amount=5)
    return if search_terms.empty?

    client.search(search_terms).first(amount).each do |tweet|
      begin
        client.favorite tweet.id
        favorited_tweets.create(
          status_id: tweet.id,
          name:      tweet.user.name,
          username:  tweet.user.username,
          image_url: tweet.user.profile_image_url_https.to_s,
          text:      tweet.text,
          posted_at: tweet.created_at
        )
      rescue
      end
    end
  end

  def search_terms
    @search_terms ||= keywords.map(&:text).join(" OR ")
  end

  def client
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
      config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :twitter_accounts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_twitter_account

  def new
    @keyword = Keyword.new
  end

  def create
    @keyword = @twitter_account.keywords.new keyword_params
    if @keyword.save
      redirect_to @twitter_account
    else
      render action: :new
    end
  end

  def destroy
    @keyword = @twitter_account.keywords.find(params[:id])
    @keyword.destroy
    redirect_to @twitter_account
  end
private

  def set_twitter_account
    @twitter_account = current_user.twitter_accounts.find(params[:twitter_account_id])
  end

  def keyword_params
    params.require(:keyword).permit(:text)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_twitter_account, except: [:index]

  def index
    @twitter_accounts = current_user.twitter_accounts
  end

  def show
  end

  def destroy
    @twitter_account.destroy
    redirect_to root_url, notice: "Account successfully deleted"
  end

private

  def set_twitter_account
    @twitter_account = current_user.twitter_accounts.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    auth = request.env["omniauth.auth"]

    twitter_account = current_user.twitter_accounts.find_or_create_by_username(
      username: auth.info.nickname,
      token: auth.credentials.token,
      secret: auth.credentials.secret,
      image_url: auth.info.image
    )

    redirect_to twitter_account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/twitter_accounts_helper.rb
module TwitterAccountsHelper
  def twitter_account_url(username)
    "https://twitter.com/#{username}"
  end

  def tweet_url(tweet)
    "https://twitter.com/#{tweet.username}/status/#{tweet.status_id}"
  end
end

app/views/keywords/_form.html.erb
<%= form_for [@twitter_account, @keyword] do |f| %>
  <%= f.text_field :text, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/keywords/new.html.erb
<h1>Add Keyword</h1>

<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fluttrly</title>
  <%= favicon_link_tag "favicon.ico" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrap">
    <%= render partial: "shared/navbar" %>

    <div class="container">
      <%= render partial: "shared/notices" %>
      <%= yield %>
    </div>
  </div>

  <%= render partial: "shared/footer" %>

</body>
</html>

app/views/main/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Favorite Tweets</h1>
    <p>Connect your Twitter account, add some search terms, and we will start automatically favoriting tweets for you!</p>

    <%= link_to "Sign Up", new_user_registration_path %>
    or
    <%= link_to "Login", new_user_session_path %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="pull-right text-muted"><%= mail_to "chris@excid3.com", "Help", subject: "I need help with Fluttrly!" %></p>
    <p class="text-muted">Copyright &copy; <%= link_to "Chris Oliver", "http://excid3.com" %> 2013</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, class: "navbar-brand" do %>
        <%= image_tag "fluttrly.png", alt: "Fluttrly", class: "img-responsive" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Twitter Accounts", twitter_accounts_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to edit_user_registration_path do %><i class="fa fa-cogs"></i><% end %></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-power-off"></i><% end %></li>

        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="alert alert-info">
    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger">
    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
    <%= alert %>
  </div>
<% end %>

app/views/twitter_accounts/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Add Twitter Account", user_omniauth_authorize_path(:twitter), class: "btn btn-default" %>
  </div>

  <h1>Twitter Accounts</h1>
</div>


<% if current_user.twitter_accounts.empty? %>
  <div class="alert alert-success"><%= link_to "Connect a Twitter Account", user_omniauth_authorize_path(:twitter) %> to get started!</div>
<% end %>

<% current_user.twitter_accounts.each do |twitter_account| %>
  <div class="twitter-account">
    <%= link_to image_tag(twitter_account.image_url, class: "img-rounded"), twitter_account %>

    <div class="twitter-account-body">
      <%= link_to twitter_account do %>
        <strong>@<%= twitter_account.username %></strong>

        <span>
          Keywords:
          <% twitter_account.keywords.each do |keyword| %>
            <span class="label label-primary"><%= keyword.text %></span>
          <% end %>

        </span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/twitter_accounts/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Delete", @twitter_account, class: "btn btn-default", method: :delete, confirm: "Are you sure you want to delete @#{@twitter_account.username}?" %>
  </div>

  <%= image_tag(@twitter_account.image_url, class: "img-rounded pull-left") %>
  <h1>@<%= @twitter_account.username %></h1>
</div>

<div class="row">
  <div class="col-sm-3">
    <h4><%= fa_icon("tags") %> Keywords</h4>
    <% if @twitter_account.keywords.empty? %>
      <p class="text-muted">No keywords added yet.</p>
    <% end %>

    <div class="form-group">
    <% @twitter_account.keywords.each do |keyword| %>
      <%= link_to twitter_account_keyword_path(@twitter_account, keyword), method: :delete, class: "btn btn-default" do %>
        <%= keyword.text %>
        <%= fa_icon("times") %>
      <% end %>
    <% end %>
  </div>

    <%= form_for [@twitter_account, Keyword.new], html: {class: "form-inline" } do |f| %>
      <div class="form-group">
        <%= f.text_field :text, placeholder: "Add Keyword", class: "form-control" %>
      </div>
      <div class="form-group">
      <%= f.submit "Add", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>

  <div class="col-sm-9">
    <h4>Recently Favorited Tweets</h4>

    <% if @twitter_account.favorited_tweets.empty? %>
      <% if @twitter_account.keywords.empty? %>
        <div class="alert alert-success"><%= fa_icon("arrow-left") %> Add a keyword to begin favoriting tweets!</div>
      <% else %>
        <div class="alert alert-info">We will begin favoriting tweets shortly!</div>
      <% end %>
    <% end %>


    <% @twitter_account.favorited_tweets.recent.sorted.each do |favorited_tweet| %>
      <div class="tweet">
        <%= link_to image_tag(favorited_tweet.image_url, class: "img-rounded"), twitter_account_url(favorited_tweet.username), target: "_blank" %>

        <p class="tweet-body">
          <span class="pull-right"><%= link_to "#{time_ago_in_words(favorited_tweet.posted_at)} ago", tweet_url(favorited_tweet) %></span>
          <%= link_to twitter_account_url(favorited_tweet.username), target: "_blank" do %>
            <span class="name"><%= favorited_tweet.name %></span>
            <span class="username">@<%= favorited_tweet.username %></span>
          <% end %>
          <span class="text"><%= Rinku.auto_link(favorited_tweet.text).html_safe %></span>
        </p>
      </div>
    <% end %>
  </div>
</div>